name: CI Build, Test & Artifact Generate

on:
  push:
    branches:
      - develop
      - feature1
  pull_request:
    branches:
      - develop
      - feature1

jobs:
  build-and-test:
    # Use self-hosted runner if available; otherwise default to ubuntu-latest.
    runs-on: [self-hosted, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Update to your target .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Run Unit Tests and Generate Test Reports
        run: |
          # Run tests and generate a TRX test report file.
          dotnet test --configuration Debug --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Publish Test Report Artifact
        if: always()  # Upload even if tests fail to allow investigation.
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: '**/TestResults/*.trx'

      - name: Build Artifacts for Download
        run: |
          # For a build pipeline, you may want to package output from the Debug build.
          # Adjust the paths as needed for your project.
          mkdir -p artifacts
          cp -r **/bin/Debug/* artifacts/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: artifacts/
