name: CI Build, Test & Artifact Upload

on:
  push:
    branches:
      - develop
      - 'feature-*'
  pull_request:
    branches:
      - develop
      - 'feature-*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Run Unit Tests and Generate Test Report
        run: |
          mkdir -p TestResults
          dotnet test --configuration Debug --no-build --logger "trx;LogFileName=TestResults/test_results.trx"

      - name: List TestResults Directory
        run: ls -la TestResults

      - name: Publish Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: test-report
         path: '**/test_results.trx'

      - name: Copy Build Output for Artifact
        run: |
          mkdir -p artifacts
          cp -r **/bin/Debug/* artifacts/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/
