name: CI Build, Test & Artifact Upload

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - develop
      - 'feature-*'

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Upload Build Artifacts to JFrog using curl
        run: |
          for file in CalculatorApp/bin/Debug/net8.0/*.dll TestProject1/bin/Debug/net8.0/*.dll; do
            curl -H "Authorization: Bearer ${{ secrets.JFROG_TOKEN }}" \
                 -T "$file" \
                 "https://trial2t885z.jfrog.io/artifactory/dotnet-nuget-local/$(basename $file)"
          done
