name: CI Build, Test & Upload to Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - 'feature-*'
  schedule:
    - cron: '30 11 * * 3,5' # Every Wednesday & Friday 5:00 PM IST

jobs:
  build-and-upload:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Run Unit Tests and Generate Test Report
        run: |
          mkdir -p TestResults
          dotnet test --configuration Debug --no-build \
            --logger "trx;LogFileName=TestResults/test_results.trx"

      - name: Upload Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ github.sha }}
          path: TestResults/test_results.trx

      - name: Pack NuGet Package (Without Changing .csproj)
        run: |
          mkdir -p artifacts
          dotnet pack --configuration Debug --output artifacts/

      - name: Verify Artifacts
        run: |
          echo "Checking Artifacts Folder..."
          ls artifacts/ || echo "Artifacts folder not found"

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: artifacts/

      - name: Upload to Artifactory
        if: always()
        run: |
          echo "Uploading to Artifactory..."
          if [ "$(ls -A artifacts/)" ]; then
            for file in artifacts/*.nupkg; do
              echo "Uploading $file..."
              curl -u "${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASSWORD }}" \
              -T $file \
              ${{ secrets.ARTIFACTORY_URL }}/api/nuget/dotnet-nuget/
            done
          else
            echo "No NuGet packages found!"
            exit 1
          fi
