name: Deploy NuGet Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install NuGet CLI
      run: sudo apt-get install nuget

    - name: Configure Artifactory Source
      run: |
        nuget sources Add -Name Artifactory -Source https://trial2t885z.jfrog.io/artifactory/api/nuget/v3/dotnet-nuget \
        -username ${{ secrets.ARTIFACTORY_USERNAME }} \
        -password ${{ secrets.ARTIFACTORY_APIKEY }}

    - name: Authenticate API Key
      run: |
        nuget setapikey ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_APIKEY }} -Source Artifactory

    - name: Push Package
      run: |
        nuget push **/*.nupkg -Source Artifactory -ApiKey ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_APIKEY }}
