name: CI Build, Test & Artifact Upload

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - develop
      - 'feature-*'

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Run Unit Tests and Generate Test Report
        run: |
          mkdir -p TestResults
          dotnet test --configuration Debug --no-build \
            --logger "trx;LogFileName=TestResults/test_results.trx"

      - name: Upload Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ github.sha }}
          path: TestResults/test_results.trx

      - name: Copy Build Output for Artifact
        run: |
          mkdir -p artifacts
          cp -r **/bin/Debug/* artifacts/

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: artifacts/

      - name: Install JFrog CLI (explicit installation)
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jfrog

      - name: Debug Token
        run: |
          echo "Token Length: ${#${{ secrets.ARTIFACTORY_PASSWORD }}}"
          echo "Artifactory URL: https://trial2t885z.jfrog.io/artifactory"

      - name: Authenticate JFrog CLI
        run: |
          jfrog config add my-artifactory-10 --artifactory-url https://trial2t885z.jfrog.io/artifactory --access-token ${{ secrets.ARTIFACTORY_PASSWORD }} --interactive=false
          echo "Checking JFrog connection..."
          jfrog rt ping || echo "JFrog connection failed"
          echo "Verifying token..."
          jfrog config show my-artifactory-10

      - name: Test JFrog Connection
        run: jfrog rt ping --server-id=my-artifactory-10

      - name: Decode Token
        run: echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | base64 --decode

      - name: Push Build Artifacts to Artifactory
        run: |
          jfrog rt u "artifacts/*" "dotnet-nuget/${{ github.sha }}/" --flat=false --build-name="dotnet-build" --build-number="${{ github.run_number }}"
          echo "JFrog Upload Exit Code: $?"
