name: CI Build, Test & Artifact Upload

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - develop
      - 'feature-*'

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jfrog

      - name: Authenticate JFrog CLI with Access Token
        run: |
          jfrog config add my-artifactory-26 \
            --artifactory-url https://trial2t885z.jfrog.io/artifactory \
            --access-token "${{ secrets.JFROG_TOKEN }}" \
            --interactive=false

      - name: Upload Build Artifacts to JFrog
        run: |
          jfrog rt u "CalculatorApp/bin/Debug/net8.0/*.dll" "dotnet-nuget-local/"
          jfrog rt u "TestProject1/bin/Debug/net8.0/*.dll" "dotnet-nuget-local/"
