name: CI Build, Test & Upload to Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - 'feature-*'
  schedule:
    - cron: '30 11 * * 3,5' # Every Wednesday & Friday 5:00 PM IST

jobs:
  build-and-upload:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build --output artifacts/

      - name: List Artifacts Folder
        run: ls artifacts/ || echo "Artifacts folder not found"

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: artifacts/

      - name: Upload to Artifactory
        if: always()
        run: |
          echo "Uploading to Artifactory..."
          ls artifacts/
          for file in artifacts/*.nupkg; do
            echo "Uploading $file to Artifactory..."
            curl -u "${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASSWORD }}" \
            -T $file \
            ${{ secrets.ARTIFACTORY_URL }}/api/nuget/dotnet-nuget/
          done
