name: SonarQube

on:
  push:  
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
      
jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          fetch-depth: 0
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Debug --no-restore

      - name: Run Unit Tests and Generate Test Report
        run: |
          mkdir -p TestResults
          dotnet test --configuration Debug --no-build --logger "trx;LogFileName=TestResults/test-results.trx"

      - name: Install SonarScanner
        run: |
         curl -sS https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
         unzip sonar-scanner.zip -d $HOME
         export PATH=$PATH:$HOME/sonar-scanner-4.6.2.2472-linux/bin
         echo "SonarScanner installed successfully"

      - name: Build and analyze with SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.projectKey=kashishrastogi03_CI-PIPELINE \
            -Dsonar.organization=kashishrastogi03 \
            -Dsonar.token="${{ secrets.SONAR_TOKEN }}" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.cs.vstest.reportsPaths=TestResults/*.trx
