name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: self-hosted  # Your CentOS Hosted Agent

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # SonarCloud needs full Git history

      - name: Setup .NET SDK
        run: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH=$HOME/.dotnet:$PATH

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Debug --no-restore

      - name: Run Tests with Coverage
        run: dotnet test --configuration Debug --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=TestResults/test-results.trx"

      - name: Move Coverage Report
        run: |
          mkdir -p coverage
          mv **/TestResults/**/coverage.cobertura.xml coverage/coverage.opencover.xml || echo "No coverage file found"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=kashishrastogi03_CI-PIPELINE
            -Dsonar.organization=kashishrastogi03
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.verbose=true
            -Dsonar.cs.opencover.reportsPaths=coverage/coverage.opencover.xml
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
